### ISSUE TITLE
Consider passing image directly to frontend

### ISSUE THREAD

**Issue by stefanv** [dmitryduev/kowalski-dev#9]
Adam Miller requested that we add median centered inverse hyperbolic sine scaling.  However, currently LogNorm is hardcoded.

```
    if ztftype != 'Difference':
        img[img <= 0] = np.median(img)
        plt.imshow(img, cmap=plt.cm.bone, norm=LogNorm(), origin='lower')
    else:
        plt.imshow(img, cmap=plt.cm.bone, origin='lower')
```

With this scaling, we could potentially get rid of the if clause.

However, perhaps it would be simplest to leave these scalings to the frontend, paving the way for using JS9.

**Comment by dmitryduev** [comment]
The respective endpoint can serve both png and fits, see [here](https://github.com/dmitryduev/kowalski-dev/blob/master/kowalski/api.py#L2690), so whenever the JS9 stuff is ready, we would just need to change a parameter in the api call. Makes sense for the png's though, so I'll implement that.

**Comment by dmitryduev** [comment]
@adamamiller I added different scaling methods in #11

This is the default so far (ZTF20aaelulu):
![image](https://user-images.githubusercontent.com/7557205/94336781-86cf4b00-ff9a-11ea-89ef-573be1d8c9e5.png)

This is what it looks like with the proposed arcsinh scaling:
![image](https://user-images.githubusercontent.com/7557205/94336843-052bed00-ff9b-11ea-9c34-1e6d2877671d.png)

To my taste, this is
![image](https://user-images.githubusercontent.com/7557205/94336811-b8e0ad00-ff9a-11ea-9683-10a0704494f8.png)

Also added zscale (might be a compromise, but requires manual fiddling in many cases):
![image](https://user-images.githubusercontent.com/7557205/94336868-34425e80-ff9b-11ea-8342-e629b664b855.png)

In the end, decided to leave it as is, since JS9 support is coming to Fritz really soon:
![image](https://user-images.githubusercontent.com/7557205/94336958-b3d02d80-ff9b-11ea-99fe-b1b8177445c9.png)

**Comment by adamamiller** [comment]
@dmitryduev indeed - for this example that baseline example doesn't seem great. Dividing everything inside the arsinh() argument by ~10 should improve what you are seeing. Though that number will vary some field to field. 

If JS9 is coming then that will correct a number of these ills so it probably isn't worth additional messing around at this point.
